# Generated by Django 5.1 on 2024-08-13 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industry',
            old_name='name',
            new_name='industry_name',
        ),
        migrations.RenameField(
            model_name='sector',
            old_name='name',
            new_name='sector_name',
        ),
    ]
