# Generated by Django 5.1 on 2024-08-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_alter_sell_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='unitary_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
