# Generated by Django 5.1 on 2024-08-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_industry_sector_buy_user_sell_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='company_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='buy',
            name='total_value',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name='buy',
            name='unitary_value',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
